---
:position: before
:position_in_additional_file_patterns: before
:position_in_class: before
:position_in_factory: before
:position_in_fixture: before
:position_in_routes: before
:position_in_serializer: before
:position_in_test: before
:classified_sort: true # Сортировать аннотации по типу данных
:exclude_controllers: true # Исключить контроллеры
:exclude_factories: true # Исключить фабрики
:exclude_fixtures: true # Исключить фикстуры
:exclude_helpers: true # Исключить хелперы
:exclude_scaffolds: true # Исключить саффолды
:exclude_serializers: false # Исключить сериализаторы
:exclude_sti_subclasses: false # Исключить дочерние STI-классы
:exclude_tests: true # Исключить тесты
:force: true # Принудительная перезапись аннотаций
:format_markdown: false
:format_rdoc: false
:format_yard: true
:frozen: false
:ignore_model_sub_dir: false
:ignore_unknown_models: false
:include_version: false
:show_check_constraints: true # Показывать ограничения атрибута
:show_complete_foreign_keys: false # Показывать внешние ключи, включая ссылающиеся таблицы и каскадные действия
:show_foreign_keys: true # Показывать внешние ключи
:show_indexes: true # Показывать индексы
:simple_indexes: false # Простые индексы (без дополнительных данных о столбцах)
:sort: false # Сортировать аннотации
:timestamp: true # Добавить временную метку
:trace: false # Выводить отладочную информацию
:with_comment: true
:with_column_comments: true
:with_table_comments: true
:active_admin: false
:command:
:debug: false
:hide_default_column_types: ''
:hide_limit_column_types: ''
:ignore_columns:
:ignore_routes:
:models: true # Аннотировать модели
:routes: false # Аннотировать маршруты
:skip_on_db_migrate: false
:target_action: :do_annotations
:wrapper:
:wrapper_close:
:wrapper_open:
:classes_default_to_s: []
:additional_file_patterns: []
:model_dir:
- app/models
:require: []
:root_dir:
- ''
